version: '3.4'
services:
  web:
    image: movieadvisor-webapi:1.0.0
    container_name: webapi-container
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - rabbitmq
      - redis
      - hangfire-db
    environment:
      # Message Broker
      - MessageBroker__Host=rabbitmq://rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest

      # Redis
      - RedisSettings__Host=redis
      - RedisSettings__Port=6379

      # Hangfire
      - ConnectionStrings__Hangfire="Data Source=127.0.0.1,1433;Initial Catalog=HangfireDB;User Id=sa;Password=S@mplePa55.;MultipleActiveResultSets=true;"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

  # hangfire:
  #   image: hangfire/hangfire
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - hangfire-db
  #   networks:
  #     - my-network
  #   restart: always

  hangfire-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: hangfire-db-container
    environment:
      SA_PASSWORD: "S@mplePa55."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
